### ISSUE TITLE
Issue with specifying image with ParentVhd

### ISSUE THREAD

**Issue by jolwh** [dataplat/dbaclone#147]
**Describe the bug**
The ParentVhd parameter doesn't seem to access a specified image or create a clone. Running a New-DcnClone as below does not return any errors or output and does not create a clone.

> New-DcnClone -SqlInstance MyInstance -ParentVhd \\path\to\image\DB1_20211115134729.vhdx -Destination Y:\CLONES\CLONE1\ -CloneName Clone1

Also tried above command with local path for the image instead of network. Same result.

Running the command with -debug gets you to the "Testing module setup" step but goes no further. When running with the UseLastFullBackup parameter it brings you through the whole process and successfully creates a clone but for our use case we need multiple images taken at different points in time so need to be able to specify an image to use for a clone.

**Environmental data**

We're running with the latest version.

Version    Name                                Repository           Description
-------    ----                                ----------           -----------
0.10.47    dbaclone                            PSGallery            Module for cloning SQL Server databases

 - PowerShell: 
PS C:\scripts> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14393  4583

**Comment by blitzmann** [comment]
I believe this is the same as #176 , which I've just submitted a fix for. I didn't see this issue before I made mine unfortunately

**Comment by jolwh** [comment]
I've tested the fix for this in the latest release. Working as expected. Thank you!
