### ISSUE TITLE
[New-DcnImage] Couldn't create access path directory

### ISSUE THREAD

**Issue by st0m1991** [dataplat/dbaclone#161]
Hello!
When using the command
`New-DcnImage -SourceSqlInstance TEST-SQL-CLONE -DestinationSqlInstance TEST-SQL-CLONE -ImageNetworkPath \\TEST-SQL-CLONE\dbaclone -Database franch_rozn_prof -CreateFullBackup`

I get an error
```
WARNING: [10:19:19][Post Import] Unsupported version of Windows
New-Partition: The disk has not been initialized.
Activity ID: {f0d2d880-ff58-45fb-b0b1-446bdeab18e2}
WARNING: [10:21:04][New-DcnImage] Couldn't create access path directory | Exception calling "SetAccessRule" with "1" argument(s): "Some or all identity references could not be translated."
```

Windows Server 2016 Standart
MS SQL 2017
Powershell 7.2.1

How to fix the problem?

**Comment by sanderstad** [comment]
This should be fixed by now. Closing the issue. If this is still a problem please reopen the issue
