### ISSUE TITLE
New-DcnClone: Errors w/ SQL Server's default location when run remotely

### ISSUE THREAD

**Issue by LowlyDBA** [dataplat/dbaclone#164]
**Before submitting the bug**
- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

**Describe the bug**
When not supplying `-Destination` to `New-DcnClone` and running this command remotely, the path resolution fails since the path is only valid on the remote host. 

I think since we're fetching from the instance's default data dir, we can safely just `+` the values together instead? That has worked for me locally. Happy to make a PR if that works as a solution.

https://github.com/dataplat/dbaclone/blob/1386e86116e4e93425a734abc56990c4f573b160/functions/clone/New-DcnClone.ps1#L237-L240

**To Reproduce**
```powershell
New-DcnClone -SqlInstance "RemoteSqlIntance" -CloneName $CloneName -Database $Database -LatestImage -Verbose
```
results in

> Join-Path : Cannot find drive. A drive with the name 'X' does not exist.
> At C:\Program Files\WindowsPowerShell\Modules\PSFramework\1.6.214\PSFramework.psm1:11474 char:21

**Expected behavior**
It should be able to handle a default data directory that doesn't exist on the local machine when the destination instance is remote.

**Comment by bortolin** [comment]
I have make PR about this, recently https://github.com/dataplat/dbaclone/pull/166

**Comment by LowlyDBA** [comment]
Awesome!
