### ISSUE TITLE
diskpart.txt created in relative path location.

### ISSUE THREAD

**Issue by DatKyle** [dataplat/dbaclone#168]
Pull Request #151 Changed the diskpart logic to use a relative path(`.\diskpart.txt`) instead of `$diskpartScriptFile` (`$env:APPDATA\dbaclone\diskpartcommand.txt`)

This has the side effect of leaving the file in the path the command was run in.

## solution
Use the `$diskpartScriptFile`, as previously, and add logic to create the file location on the remote instance if it doesn't exist. not sure if we want to remove the file after we have finished with it.

I'm in the process of fixing this, just raising the issue so others know of the issue.

**Comment by lowlydba** [comment]
@DatKyle Are you still working on this? I've hit a scenario where the txt file still had a lock on it and caused new clones to fail, so I think cleanup would be a worthwhile thing to include.

If not, I will open a separate bug/PR for the cleanup piece.

**Comment by lowlydba** [comment]
Not sure if this is still needed after https://github.com/dataplat/dbaclone/pull/205 adds functionality to cleanup the file.

**Comment by DatKyle** [comment]
No longer needed as stated above.
